blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.ensemble.ai/workspace
    about: Check the docs before opening an issue
  - name: Discussions
    url: https://github.com/ensemble-ai/workspace/discussions
    about: Ask questions and discuss ideas
