#!/usr/bin/env node
/**
 * Build the Ensemble guest runtime.
 *
 * Output: dist/runtime.js (IIFE that attaches to window.Ensemble)
 *         dist/runtime.css (Tailwind v4 output for everything the runtime uses)
 *         dist/assets.js / assets.d.ts (those two as string exports for the worker)
 *
 * Workspace's worker imports dist/assets.js and serves the strings from
 * /_ensemble/runtime/v1/runtime.{js,css}.
 *
 * Usage:
 *   node build.js          # development build
 *   node build.js --prod   # minified production build
 */

import * as esbuild from "esbuild";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const isProd = process.argv.includes("--prod") || process.env.NODE_ENV === "production";
const distDir = join(__dirname, "dist");

if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });

async function buildJS() {
  await esbuild.build({
    entryPoints: [join(__dirname, "src", "runtime.tsx")],
    bundle: true,
    outfile: join(distDir, "runtime.js"),
    format: "iife",
    globalName: "__EnsembleRuntimeBundle",
    platform: "browser",
    target: ["es2020"],
    minify: isProd,
    sourcemap: !isProd,
    jsx: "automatic",
    jsxImportSource: "react",
    define: {
      "process.env.NODE_ENV": JSON.stringify(isProd ? "production" : "development"),
    },
    // Preact may leak in via pnpm hoisting; alias to react.
    alias: {
      preact: "react",
      "preact/hooks": "react",
      "preact/compat": "react",
      "preact/jsx-runtime": "react/jsx-runtime",
    },
  });
  console.log("[guest-runtime] JS built:", join(distDir, "runtime.js"));
}

async function buildCSS() {
  // Tailwind v4 entry pulls in ui's globals.css plus walks ui's compiled
  // dist for class strings. The output is the complete utility set the
  // runtime's bundled components reference.
  const cssEntry = join(__dirname, "src", "runtime.css");
  writeFileSync(
    cssEntry,
    `@import "@ensemble-edge/ui/globals.css";\n` +
      // Walk runtime sources (we use classes there too).
      `@source "./runtime.tsx";\n`,
  );
  const outputCss = join(distDir, "runtime.css");
  try {
    execSync(
      `npx @tailwindcss/cli -i ${cssEntry} -o ${outputCss} ${isProd ? "--minify" : ""}`,
      { cwd: __dirname, stdio: "inherit" },
    );
    console.log("[guest-runtime] CSS built:", outputCss);
  } catch (err) {
    console.error("[guest-runtime] CSS build failed:", err);
    throw err;
  }
}

function generateAssets() {
  const js = readFileSync(join(distDir, "runtime.js"), "utf-8");
  const css = readFileSync(join(distDir, "runtime.css"), "utf-8");

  const moduleContent = `/**
 * Guest Runtime Assets (Auto-generated by build.js)
 *
 * Exports the bundled runtime JS and CSS as strings, plus the version.
 * Imported by @ensemble-edge/core to serve from /_ensemble/runtime/v1/.
 *
 * DO NOT EDIT — regenerated on every build.
 */

export const RUNTIME_VERSION = 1;
export const RUNTIME_JS = ${JSON.stringify(js)};
export const RUNTIME_CSS = ${JSON.stringify(css)};
`;

  writeFileSync(join(distDir, "assets.js"), moduleContent);
  writeFileSync(
    join(distDir, "assets.d.ts"),
    `export declare const RUNTIME_VERSION: 1;\nexport declare const RUNTIME_JS: string;\nexport declare const RUNTIME_CSS: string;\n`,
  );
  console.log("[guest-runtime] Assets module generated:", join(distDir, "assets.js"));
}

async function main() {
  try {
    await buildJS();
    await buildCSS();
    generateAssets();
    console.log("[guest-runtime] Build complete.");
  } catch (error) {
    console.error("[guest-runtime] Build failed:", error);
    process.exit(1);
  }
}

main();
