#!/usr/bin/env node
/**
 * Build script for Ensemble Workspace Shell
 *
 * Bundles the React shell SPA into a single JS file that can be
 * served from the Worker and rendered client-side.
 *
 * CSS is built separately via Tailwind CLI (see npm run build:css).
 */

import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const isWatch = process.argv.includes('--watch');
const isProd = process.argv.includes('--prod') || process.env.NODE_ENV === 'production';

/**
 * Build the shell client bundle.
 */
async function buildShellClient() {
  const outdir = join(__dirname, 'dist', 'shell');

  // Ensure output directory exists
  if (!existsSync(outdir)) {
    mkdirSync(outdir, { recursive: true });
  }

  const buildOptions = {
    entryPoints: [join(__dirname, 'src', 'shell', 'client.tsx')],
    bundle: true,
    outfile: join(outdir, 'shell.js'),
    format: 'esm',
    platform: 'browser',
    target: ['es2020'],
    minify: isProd,
    sourcemap: !isProd,
    jsx: 'automatic',
    jsxImportSource: 'react',
    define: {
      'process.env.NODE_ENV': JSON.stringify(isProd ? 'production' : 'development'),
    },
  };

  if (isWatch) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log('Watching for changes...');
  } else {
    const result = await esbuild.build(buildOptions);
    console.log('Shell client built:', join(outdir, 'shell.js'));

    // Report bundle size
    const stats = await esbuild.analyzeMetafile(
      (await esbuild.build({ ...buildOptions, metafile: true })).metafile
    );
    console.log('Bundle analysis:\n', stats);
  }
}

/**
 * Generate a TypeScript module that exports the shell assets as strings.
 * This allows the Worker to import and serve them directly.
 *
 * Note: CSS is built by Tailwind CLI before this script runs.
 */
async function generateShellAssetsModule() {
  const outdir = join(__dirname, 'dist', 'shell');
  const shellJs = readFileSync(join(outdir, 'shell.js'), 'utf-8');
  const shellCss = readFileSync(join(outdir, 'shell.css'), 'utf-8');

  const moduleContent = `/**
 * Shell Assets Module (Auto-generated)
 *
 * This module exports the bundled shell JS and CSS as strings.
 * Generated by build.js - do not edit manually.
 */

export const SHELL_JS = ${JSON.stringify(shellJs)};

export const SHELL_CSS = ${JSON.stringify(shellCss)};
`;

  writeFileSync(join(__dirname, 'src', 'shell', 'assets.generated.ts'), moduleContent);
  console.log('Shell assets module generated:', join(__dirname, 'src', 'shell', 'assets.generated.ts'));
}

// Run builds
async function main() {
  try {
    // Build JS bundle (CSS is built by Tailwind CLI via npm run build:css)
    await buildShellClient();

    // Generate assets module after builds complete
    await generateShellAssetsModule();

    console.log('Build complete!');
  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
}

main();
