#!/usr/bin/env node
/**
 * @ensemble-edge/shell — Build Script
 *
 * Builds the React shell SPA into dist/shell.js + dist/shell.css,
 * then generates dist/assets.js which exports them as strings
 * for the Worker to serve.
 *
 * Usage:
 *   node build.js          # One-off build
 *   node build.js --watch  # Watch mode
 *   node build.js --prod   # Minified production build
 */

import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const isWatch = process.argv.includes('--watch');
const isProd = process.argv.includes('--prod') || process.env.NODE_ENV === 'production';
const distDir = join(__dirname, 'dist');

async function buildCSS() {
  const inputCss = join(__dirname, 'src', 'styles', 'globals.css');
  const outputCss = join(distDir, 'shell.css');

  if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });

  try {
    execSync(
      `npx tailwindcss -i ${inputCss} -o ${outputCss} ${isProd ? '--minify' : ''}`,
      { cwd: __dirname, stdio: 'inherit' }
    );
    console.log('[shell] CSS built:', outputCss);
  } catch (err) {
    console.error('[shell] CSS build failed:', err);
    throw err;
  }
}

async function buildJS() {
  if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });

  const buildOptions = {
    entryPoints: [join(__dirname, 'src', 'client.tsx')],
    bundle: true,
    outfile: join(distDir, 'shell.js'),
    format: 'esm',
    platform: 'browser',
    target: ['es2020'],
    minify: isProd,
    sourcemap: !isProd,
    jsx: 'automatic',
    jsxImportSource: 'react',
    define: {
      'process.env.NODE_ENV': JSON.stringify(isProd ? 'production' : 'development'),
    },
    // Preact leaks in via pnpm hoisting but must not be bundled.
    // Alias preact → react so any transitive preact imports use React.
    alias: {
      'preact': 'react',
      'preact/hooks': 'react',
      'preact/compat': 'react',
      'preact/jsx-runtime': 'react/jsx-runtime',
    },
  };

  if (isWatch) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log('[shell] Watching for JS changes...');
  } else {
    await esbuild.build(buildOptions);
    console.log('[shell] JS built:', join(distDir, 'shell.js'));
  }
}

function generateAssets() {
  const shellJs = readFileSync(join(distDir, 'shell.js'), 'utf-8');
  const shellCss = readFileSync(join(distDir, 'shell.css'), 'utf-8');

  const moduleContent = `/**
 * Shell Assets (Auto-generated by build.js)
 *
 * Exports the bundled shell JS and CSS as strings.
 * Imported by @ensemble-edge/core to serve from the Worker.
 *
 * DO NOT EDIT — regenerated on every build.
 */

export const SHELL_JS = ${JSON.stringify(shellJs)};

export const SHELL_CSS = ${JSON.stringify(shellCss)};
`;

  writeFileSync(join(distDir, 'assets.js'), moduleContent);
  console.log('[shell] Assets module generated:', join(distDir, 'assets.js'));
}

async function main() {
  try {
    await buildCSS();
    await buildJS();
    if (!isWatch) {
      generateAssets();
    }
    console.log('[shell] Build complete!');
  } catch (error) {
    console.error('[shell] Build failed:', error);
    process.exit(1);
  }
}

main();
